# Generated by Django 4.1.4 on 2023-08-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_project_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
