# Generated by Django 4.1.4 on 2023-09-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_project_author_alter_result_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='student_id',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
